### PR TITLE
Add check for signed underlying type.

### PR DESCRIPTION
**Pull request by andreasbuhr**
So please explain again why this is a bad idea.

### CODE REVIEW

**Comment by tobias-loew** [comment]
I'm not sure if users will appreciate this.
Yes, to be absolutely save, it it necessary, but all known C++ compilers always used two's complement  for signed integers.
IMHO, it seems to pedantic.
We could make the check optional by either a macro or an entry in boost::flags::options (see branch feature/logical_and).
What do you think?

**Comment by andreasbuhr** [comment]
Currently, the documentation states:

> But, defining the underlying type for unscoped enumerations is crutial!

This is in **bold**. With an exclamation mark! And "crucial" is very strong wording.

But from our discussion, I get the impression it's not that important. So I'd suggest to change the documentation. I propose to move all the text around the signedness of the underlying type into a box which has the heading "To the language lawyers".

In addition, offering this check as an option may be nice. For those language lawyers.

**Comment by tobias-loew** [comment]
I think we're talking about two different things:

- signedness of the underlying type for pre C++20 code: 
  - this is more or less pedantic
  - it can be checked by a type-trait, thus we can add an option for the language lawyers

- unscope enums without an explicit specified underlying-type
  - this causes UB, e.g. when bitwise negation is used 
  - it cannot be detected by a type-trait: there is no information with std::underlying_type if it was specified explicitly or deduced by the compiler

IMHO, the bold line is not only for language lawyers: I got warnings (promoted to errors) in the tests with new clang version, that choked on constant expressions with "unscoped, no explicit underlying-type" enums.

clang trunk already turned it into an error:
https://godbolt.org/z/79vWe3ov1

**Comment by andreasbuhr** [comment]
> IMHO, the bold line is not only for language lawyers: I got warnings (promoted to errors) in the tests with new clang version, that choked on constant expressions with "unscoped, no explicit underlying-type" enums.
> 
> clang trunk already turned it into an error: https://godbolt.org/z/79vWe3ov1

Ah I understand.

And why is the complement represented by the enum? Could you represent the complement by the underlying type of enum?

**Comment by tobias-loew** [comment]
Interesting idea! Have to think about it.

**Comment by tobias-loew** [comment]
I made a new branch feature/unsigned_test and a PR. 
In this branch, template complement uses  std::underlying_type<enum>::type as value_type, so no problem with bitwise complement and the mysterious "hypothetical value type"
(Please ignore the bad name of the branch)

**Comment by tobias-loew** [comment]
#31 is merged into main. I'll close this PR

**Pull request closed without merging**
